# Clase 4 : Programación con arrays: introducción a NumPy

In [2]:
import math

math.log(3)

1.0986122886681098

In [3]:
import random 
random.randint(0,10)

2

In [4]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



## NumPy y ndarrays

* La librería Numpy provee una forma particular de array llamada ndarray o Numpy Array.
* Recordar: los ndarrays, al ser un tipo de array, sólo pueden almacenar datos de un mismo tipo.

In [18]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

**Numpy arrays**

In [6]:
import numpy as np
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Construyendo ndarrays**

In [7]:
Np_cero = np.zeros(10)
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
Np_cero_int = np.zeros(10, dtype=int)
Np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
Np_uno = np.ones(10)
Np_uno

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
Np_relleno = np.full(10,256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [11]:
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
Np_random_dimensiones = np.random.randint(10, size=(3, 4))
Np_random_dimensiones

array([[8, 0, 3, 1],
       [9, 2, 2, 6],
       [5, 6, 0, 0]])

### **Propiedades de los Arrays**

Podemos acceder a distintas propiedades de los arreglos:

In [13]:
Np_random_dimensiones.ndim

2

In [14]:
Np_random_dimensiones.shape

(3, 4)

In [15]:
Np_random_dimensiones.size

12

Inspeccionemos un poco nuestros Numpy arrays

In [16]:
Np_random_dimensiones.dtype

dtype('int32')

In [17]:
Np_random_dimensiones.itemsize

4

In [18]:
Np_random_dimensiones.nbytes

48

### **Indexado y acceso**

In [19]:
print(Np_rango)

[0 1 2 3 4 5 6 7 8 9]


Primeros cuatro

In [20]:
Np_rango[:3]

array([0, 1, 2])

Desde el cuarto

In [21]:
Np_rango[3:]

array([3, 4, 5, 6, 7, 8, 9])

Desde el quinto al séptimo

In [22]:
Np_rango[4:7]

array([4, 5, 6])

De dos en dos

In [23]:
Np_rango[::2]

array([0, 2, 4, 6, 8])

Desde atrás, de dos en dos

In [24]:
Np_rango[::-2]

array([9, 7, 5, 3, 1])

### arreglos multidimensionales

In [25]:
Np_random_dimensiones

array([[8, 0, 3, 1],
       [9, 2, 2, 6],
       [5, 6, 0, 0]])

Tercera fila, todas las columnas

In [26]:
Np_random_dimensiones[2,]

array([5, 6, 0, 0])

Primeras dos filas, primeras dos columnas

In [27]:
Np_random_dimensiones[:2, :2]

array([[8, 0],
       [9, 2]])

Tercera fila, cuarta columna

In [28]:
Np_random_dimensiones[2, 3]

0

### Reshape, concatenación, splitting


Si tuviésemos que rellenar una grilla de 8x8 con números desde 1 a 64

#### Reshape

In [29]:
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

#### Concatenación

In [32]:
Array_1 = np.random.randint(10, size=5)
Array_2 = np.random.randint(10, size=5)
Arrays_concatenados = np.concatenate([Array_1, Array_2])
print(Arrays_concatenados)

[9 8 7 8 3 1 9 8 6 5]


El método vstack apila verticalmente

In [40]:
# conda install -c conda-forge tabulate
from tabulate import tabulate

In [33]:
Array_extra = np.array([[10],[20]])
Array_extra

array([[10],
       [20]])

In [42]:
print(tabulate(Array_extra))

--
10
20
--


In [34]:
Array_apilados_v = np.vstack([Array_extra, Array_extra])
Array_apilados_v

array([[10],
       [20],
       [10],
       [20]])

In [43]:
print(tabulate(Array_apilados_v))

--
10
20
10
20
--


El método hstack apila horizontalmente

In [35]:
Array_apilados_h = np.hstack([Array_extra, Array_extra])
Array_apilados_h

array([[10, 10],
       [20, 20]])

In [44]:
print(tabulate(Array_apilados_h))

--  --
10  10
20  20
--  --


#### Splitting

In [45]:
Arrays_concatenados

array([9, 8, 7, 8, 3, 1, 9, 8, 6, 5])

In [46]:
Array_partido = np.split(Arrays_concatenados, [2])
Array_partido

[array([9, 8]), array([7, 8, 3, 1, 9, 8, 6, 5])]

Dos puntos de corte

In [47]:
Array_partido_2 = np.split(Arrays_concatenados, [2, 8])
Array_partido_2

[array([9, 8]), array([7, 8, 3, 1, 9, 8]), array([6, 5])]

Podemos desarmar el arreglo y guardarlo en variables distintas

In [48]:
Parte_1, Parte_2, Parte_3= np.split(Arrays_concatenados, [2, 8])

In [51]:
print(Parte_1)

[9 8]


hsplit realiza cortes verticales

In [67]:
Ajedrez_partido_1 = np.hsplit(Ajedrez_64, [4])
print(Ajedrez_partido_1)

[array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20],
       [25, 26, 27, 28],
       [33, 34, 35, 36],
       [41, 42, 43, 44],
       [49, 50, 51, 52],
       [57, 58, 59, 60]]), array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [21, 22, 23, 24],
       [29, 30, 31, 32],
       [37, 38, 39, 40],
       [45, 46, 47, 48],
       [53, 54, 55, 56],
       [61, 62, 63, 64]])]


In [68]:
Ajedrez_partido_2 = np.vsplit(Ajedrez_64, [4])
print(Ajedrez_partido_2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32]]), array([[33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])]


### Agregaciones y Operaciones vectorizadas

In [69]:
Array_aleatorio = np.random.randint(10, size=10)
print(Array_aleatorio)
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma / np.size(Array_aleatorio)

[8 8 8 6 8 1 6 2 7 1]


In [73]:
Array_aleatorio.sum()

55

In [74]:
Array_aleatorio.mean()

5.5

In [75]:
Array_aleatorio.max()

8

In [76]:
np.median(Array_aleatorio)

6.5

In [77]:
np.std(Array_aleatorio)

2.8372521918222215

In [78]:
np.var(Array_aleatorio)

8.05

#### Operaciones vectorizadas

In [94]:
Array_1 = np.random.randint(10, size=2)
print(Array_1)
Array_2 = np.random.randint(10, size=2)
print(Array_2)

[0 5]
[9 2]


In [95]:
np.add(Array_1, Array_2)

array([9, 7])

In [96]:
Array_1 + Array_2

array([9, 7])

In [97]:
np.matmul(Array_1, Array_2)

10

## Desafio generico

In [110]:
#1.Generar un array aleatorio de 50 elementos. Calcular la suma correspondiente
#2. Usen np.random.randint(10, size=100)
#3. Usen el metodo sum()

In [105]:
#1.Sobreescribir la función de factorial por funciones y calculos que solo usen metodos de numpy
#2.Recordar usar el metodo .prod()
#3.Usen la secuencia del metodo .arange()


def factorial(x):
    fac = 1
    for i in range(1,x+1):
        fac *= i  # fac =  fac * i
    return(fac)

print("Resultado del factorial es: ", factorial(6))

Resultado del factorial es:  720


In [5]:
#1. Bajar el archivo en un archivo .csv en https://docs.google.com/spreadsheets/d/15Stnum8mI9QdwF9ZiPFCe3_qG9XyZyNzmOSIDunzPjA/view#gid=255849258
#2. Limpiarlo sin que contenga string (columna )
#3. Calcular media
from numpy import loadtxt

loadtxt(r'[Su RUTA]/[NOMBRE DEL ARCHIVO.csv]')

2992140697.017699