# Clase 4 : Programación con arrays: introducción a NumPy

In [7]:
import math

math.log(5)

1.6094379124341003

In [9]:
import random 
random.randint(0,10)

8

In [4]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



## NumPy y ndarrays

* La librería Numpy provee una forma particular de array llamada ndarray o Numpy Array.
* Recordar: los ndarrays, al ser un tipo de array, sólo pueden almacenar datos de un mismo tipo.

In [18]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

**Numpy arrays**

In [10]:
import numpy as np
Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Construyendo ndarrays**

In [11]:
Np_cero = np.zeros(10)
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
Np_cero_int = np.zeros(10, dtype=int)
Np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
Np_uno = np.ones(10)
Np_uno

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
Np_relleno = np.full(10,256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [15]:
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
Np_random_dimensiones = np.random.randint(10, size=(3, 4))
Np_random_dimensiones

array([[5, 3, 4, 5],
       [9, 6, 4, 1],
       [4, 9, 0, 1]])

### **Propiedades de los Arrays**

Podemos acceder a distintas propiedades de los arreglos:

In [13]:
Np_random_dimensiones.ndim

2

In [14]:
Np_random_dimensiones.shape

(3, 4)

In [15]:
Np_random_dimensiones.size

12

Inspeccionemos un poco nuestros Numpy arrays

In [16]:
Np_random_dimensiones.dtype

dtype('int32')

In [17]:
Np_random_dimensiones.itemsize

4

In [18]:
Np_random_dimensiones.nbytes

48

### **Indexado y acceso**

In [16]:
print(Np_rango)

[0 1 2 3 4 5 6 7 8 9]


Primeros cuatro

In [17]:
Np_rango[:3]

array([0, 1, 2])

Desde el cuarto

In [18]:
Np_rango[3:]

array([3, 4, 5, 6, 7, 8, 9])

Desde el quinto al séptimo

In [19]:
Np_rango[4:7]

array([4, 5, 6])

De dos en dos

In [20]:
Np_rango[::2]

array([0, 2, 4, 6, 8])

Desde atrás, de dos en dos

In [23]:
Np_rango[::-3]

array([9, 6, 3, 0])

### arreglos multidimensionales

In [26]:
Np_random_dimensiones

array([[5, 3, 4, 5],
       [9, 6, 4, 1],
       [4, 9, 0, 1]])

Tercera fila, todas las columnas

In [27]:
Np_random_dimensiones[2,]

array([4, 9, 0, 1])

Primeras dos filas, primeras dos columnas

In [28]:
Np_random_dimensiones[:2, :2]

array([[5, 3],
       [9, 6]])

Tercera fila, cuarta columna

In [29]:
Np_random_dimensiones[2, 3]

1

### Reshape, concatenación, splitting


Si tuviésemos que rellenar una grilla de 8x8 con números desde 1 a 64

#### Reshape

In [30]:
array_0 = np.arange(1,65)
type(array_0)

numpy.ndarray

In [51]:
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

#### Concatenación

In [41]:
Array_1 = np.random.randint(10, size=5)
Array_2 = np.random.randint(10, size=5)
Arrays_concatenados = np.concatenate([Array_1, Array_2])
print(Arrays_concatenados)

[7 6 8 2 4 8 9 3 8 2]


El método vstack apila verticalmente

In [34]:
# conda install -c conda-forge tabulate
from tabulate import tabulate

In [32]:
Array_extra = np.array([[10],[20]])
Array_extra

array([[10],
       [20]])

In [35]:
print(tabulate(Array_extra))

--
10
20
--


In [36]:
Array_apilados_v = np.vstack([Array_extra, Array_extra])
Array_apilados_v

array([[10],
       [20],
       [10],
       [20]])

In [37]:
print(tabulate(Array_apilados_v))

--
10
20
10
20
--


El método hstack apila horizontalmente

In [38]:
Array_apilados_h = np.hstack([Array_extra, Array_extra])
Array_apilados_h

array([[10, 10],
       [20, 20]])

In [39]:
print(tabulate(Array_apilados_h))

--  --
10  10
20  20
--  --


#### Splitting

In [42]:
Arrays_concatenados

array([7, 6, 8, 2, 4, 8, 9, 3, 8, 2])

In [44]:
Array_partido = np.split(Arrays_concatenados, [5])
Array_partido

[array([7, 6, 8, 2, 4]), array([8, 9, 3, 8, 2])]

Dos puntos de corte

In [45]:
Array_partido_2 = np.split(Arrays_concatenados, [2, 8])
Array_partido_2

[array([7, 6]), array([8, 2, 4, 8, 9, 3]), array([8, 2])]

Podemos desarmar el arreglo y guardarlo en variables distintas

In [47]:
Parte_1, Parte_2, Parte_3= np.split(Arrays_concatenados, [2, 8])

In [49]:
print(Parte_3)

[8 2]


hsplit realiza cortes verticales

In [52]:
Ajedrez_partido_1 = np.hsplit(Ajedrez_64, [2])
print(Ajedrez_partido_1)

[array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7,  8],
       [11, 12, 13, 14, 15, 16],
       [19, 20, 21, 22, 23, 24],
       [27, 28, 29, 30, 31, 32],
       [35, 36, 37, 38, 39, 40],
       [43, 44, 45, 46, 47, 48],
       [51, 52, 53, 54, 55, 56],
       [59, 60, 61, 62, 63, 64]])]


In [53]:
Ajedrez_partido_2 = np.vsplit(Ajedrez_64, [4])
print(Ajedrez_partido_2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32]]), array([[33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])]


### Agregaciones y Operaciones vectorizadas

In [54]:
Array_aleatorio = np.random.randint(10, size=10)
print(Array_aleatorio)
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma / np.size(Array_aleatorio)

[4 9 7 5 1 4 7 3 1 2]


In [73]:
Array_aleatorio.sum()

55

In [74]:
Array_aleatorio.mean()

5.5

In [75]:
Array_aleatorio.max()

8

In [76]:
np.median(Array_aleatorio)

6.5

In [77]:
np.std(Array_aleatorio)

2.8372521918222215

In [78]:
np.var(Array_aleatorio)

8.05

#### Operaciones vectorizadas

In [55]:
Array_1 = np.random.randint(10, size=2)
print(Array_1)
Array_2 = np.random.randint(10, size=2)
print(Array_2)

[3 9]
[7 7]


In [56]:
np.add(Array_1, Array_2)

array([10, 16])

In [57]:
Array_1 + Array_2

array([10, 16])

In [59]:
np.matmul(Array_1, Array_2)

84

## Desafio generico

In [61]:
#1.Generar un array aleatorio de 50 elementos. Calcular la suma correspondiente
#2. Usen np.random.randint(10, size=100)
#3. Usen el metodo sum()

np.random.randint(10, size=50).sum()

208

In [63]:
#1.Sobreescribir la función de factorial por funciones y calculos que solo usen metodos de numpy
#2.Recordar usar el metodo .prod()
#3.Usen la secuencia del metodo .arange()


def factorial(x):
    fac = 1
    for i in range(1,x+1):
        fac *= i  # fac =  fac * i
    return(fac)

print("Resultado del factorial es: ", factorial(5))

Resultado del factorial es:  120


In [69]:
np.arange(1,6).prod()

120

In [71]:
#1. Bajar el archivo en un archivo .csv en https://docs.google.com/spreadsheets/d/15Stnum8mI9QdwF9ZiPFCe3_qG9XyZyNzmOSIDunzPjA/view#gid=255849258
#2. Limpiarlo sin que contenga string (columna )
#3. Calcular media
from numpy import loadtxt

loadtxt(r'C:/Users/mi13966/Downloads/Desafio.csv').mean()

2992140697.017699